<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NAUSP-ELPT82228" failures="1" tests="3" name="test" time="28.068" errors="0" timestamp="2020-06-14T16:19:47 EDT">
  <testcase classname="test.DemoTestClass" name="testFail" time="11.879">
    <failure type="java.lang.AssertionError" message="Executing Failed Test Method">
      <![CDATA[java.lang.AssertionError: Executing Failed Test Method
at test.DemoTestClass.testFail(DemoTestClass.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testFail -->
  <testcase classname="test.DemoTestClass" name="testSkip" time="4.598">
    <skipped/>
  </testcase> <!-- testSkip -->
  <testcase classname="test.DemoTestClass" name="testSuccessful" time="2.662"/>
</testsuite> <!-- test -->
